#
# Module manifest for module 'ActiveDirectory'
#
# Generated by: Neil White
#
# Generated on: 6/13/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ActiveDirectory.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '7f3b8155-220f-427d-aacb-b2f6f8f30c72'

# Author of this module
Author = 'Neil White'

# Company or vendor of this module
CompanyName = 'Neil White'

# Copyright statement for this module
Copyright = '(c) 2022-2026 Neil White. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Functional replacement for the Active Directory module. Effectively allows you to use Windows official AD Cmdlets without installing RSAT or equivalent Windows feature.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.1.0'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @("ActiveDirectory.Classes")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    "Get-ADUser"
    "Get-ADGroup"
    "Get-ADGroupMember"
    "Get-ADPrincipalGroupMembership"
    # "Convert-ADCnToGroupName"
    # "Convert-UserToLDAPUser"
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = $()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = "ActiveDirectory.psd1","ActiveDirectory.psm1"

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("ActiveDirectory")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/variableresistor/ActiveDirectory/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/variableresistor/ActiveDirectory'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

